package net.binarypaper.servlet.person;

import java.util.List;
import java.util.Optional;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

import com.fasterxml.jackson.annotation.JsonView;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;

@RestController
@RequestMapping(path = "person", produces = { MediaType.APPLICATION_JSON_VALUE })
@CrossOrigin(origins = { "${application.cors.origins}" })
@Tag(name = "Person API", description = "Manage person database entities")
@RequiredArgsConstructor
public class PersonController {

    private final PersonRepository personRepository;

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(summary = "Create a new person", description = "Create a new person. The unique person id will be generated by the system.")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "The person was created"),
            @ApiResponse(responseCode = "400", description = "Invalid person details", content = @Content)
    })
    @JsonView(Person.Views.View.class)
    @Transactional
    public Person createPerson(
            @RequestBody @Parameter(description = "The person to create") 
            @Validated(Person.Views.Create.class) @JsonView(Person.Views.Create.class) Person person) {
        return personRepository.save(person);
    }

    @GetMapping
    @Operation(summary = "Get a list of all persons", description = "Get a list of all persons")
    @ApiResponses({ @ApiResponse(responseCode = "200", description = "List of all persons") })
    @JsonView(Person.Views.List.class)
    public List<Person> getAllPersons() {
        return personRepository.findAll();
    }

    @GetMapping(path = "{id}")
    @Operation(summary = "Get a person by id", description = "Get a person by id")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Person returned"),
            @ApiResponse(responseCode = "404", description = "Invalid person id", content = @Content)
    })
    @JsonView(Person.Views.View.class)
    public Person getPersonById(
            @PathVariable @Parameter(description = "Id of the person to get", example = "1") Long id) {
        Optional<Person> person = personRepository.findById(id);
        if (person.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Invalid id");
        }
        return person.get();
    }

    @PutMapping(path = "{id}")
    @Operation(summary = "Update an existing person", description = "Update an existing person.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "The person was updated"),
            @ApiResponse(responseCode = "400", description = "Invalid person details", content = @Content)
    })
    @JsonView(Person.Views.View.class)
    @Transactional
    public Person updatePerson(
            @PathVariable @Parameter(description = "Id of the person to update", example = "1") Long id,
            @RequestBody @Parameter(description = "The person to update") 
            @Validated(Person.Views.Update.class) @JsonView(Person.Views.Update.class) Person person) {
        getPersonById(id);
        if (!id.equals(person.getId())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "The id in the path does not match the id in the request body");
        }
        return personRepository.save(person);
    }

    @DeleteMapping(path = "{id}")
    @Operation(summary = "Delete a person by id", description = "Delete a person by id")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Person deleted", content = @Content),
            @ApiResponse(responseCode = "404", description = "Invalid person id", content = @Content)
    })
    @Transactional
    public void deletePersonById(
            @PathVariable @Parameter(description = "Id of the person to delete", example = "1") Long id) {
        getPersonById(id);
        personRepository.deleteById(id);
    }
}